language: node_js
node_js:
  - 7
  - 8
  - 9
script:
  - npm run coverage
cache:
  directories:
    - "node_modules"
install:
  - npm install -g coveralls
after_success:
  - coveralls < ./coverage/lcov.info